name: test1

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "feature/**"
      - dev 
    paths:
      - "envs/**/envs_a/**"
      - "services/service_a/**"
      - "!exclude/**"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello World!"
